//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 课程安排.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class classes
    {
        public int id { get; set; }
        [Required(ErrorMessage = "请填写班级名称")]
        [StringLength(20,MinimumLength =2, ErrorMessage = "班级名称至少包含两个字符")]
        [Display(Name ="班级名称")]
        public string name { get; set; }
        [Display(Name = "班主任")]
        public Nullable<int> teacherid { get; set; }
    }
}
