//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 课程安排.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class coursemenagements
    {
        public int Id { get; set; }
        [Display(Name ="班级")]
        public int classid { get; set; }
        [Display(Name ="科目")]
        public int courseid { get; set; }
        [Display(Name ="教师")]
        public int teacherid { get; set; }
    }
}
