//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 课程安排.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class kechenganpaiEntities : DbContext
    {
        public kechenganpaiEntities()
            : base("name=kechenganpaiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<classes> classes { get; set; }
        public virtual DbSet<teacher> teacher { get; set; }
        public virtual DbSet<coursemenagements> coursemenagements { get; set; }
        public virtual DbSet<kebiao> kebiao { get; set; }
        public virtual DbSet<students> students { get; set; }
        public virtual DbSet<daohanglanguanli> daohanglanguanli { get; set; }
        public virtual DbSet<ActionLink> ActionLink { get; set; }
        public virtual DbSet<SideBar> SideBar { get; set; }
        public virtual DbSet<Navbar> Navbar { get; set; }
    }
}
