//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 课程安排.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class students
    {
        public int id { get; set; }
        [Display(Name = "学生姓名")]
        public string name { get; set; }
        
        [Display(Name = "所在班级")]
        public string classid { get; set; }
       
    }
}
